### PR TITLE
Include hipstdpar in rocThrust packages

### PR DESCRIPTION
**Pull request by lawruble13**
Include the hipstdpar-lib.hpp file in rocThrust installations, and set up the rocThrust package to be installed when the `hipstdpar` package is requested.

### CODE REVIEW

**Comment by lawruble13** [comment]
Note that this also depends on [rocm-cmake PR #162](https://github.com/RadeonOpenCompute/rocm-cmake/pull/162) to correct some behaviour around the `PROVIDES` field and variables.

**Comment by saadrahim** [comment]
Why is hipstdpar in rocThrust? I do not understand the logic.

**Comment by lawruble13** [comment]
> Why is hipstdpar in rocThrust? I do not understand the logic.

This was the proposed solution because hipstdpar is a single header, that depends on rocThrust. While it could be its own additional package, it was considered simpler to include the header file in rocThrust and add the correct name to the provides field.

**Comment by doctorcolinsmith** [comment]
I think the packaging additon is fine, but a quick addition to the README and CHANGELOG should be included.

**Review by saadrahim — APPROVED** [review]

**Review by AlexVlx — APPROVED** [review]
LGTM, thanks.

**Pull request merged**
