### PR TITLE
Added copy_if on device test case

### PR DESCRIPTION
**Pull request by neon60**
Added copy_if on device test case

### CODE REVIEW

**Comment by doctorcolinsmith** [comment]
The same failures are seen on https://github.com/ROCmSoftwarePlatform/rocThrust/pull/145.  Unclear which changeset is causing the fails.

**Comment by neon60** [comment]
> The same failures are seen on #145. Unclear which changeset is causing the fails.

We can build on our side. Can you send the build error?

**Comment by saadrahim** [comment]
I am trying to figure out what it is. We didn't use ninja for the builds. I do not think that should impact this but I can add that.

**Comment by neon60** [comment]
Could someone restart the CI run? It should pass now, with the latest rocPRIM develop branch.

**Review by saadrahim — APPROVED** [review]

**Pull request merged**
