### PR TITLE
Handle the return value in malloc_and_free.h

### PR DESCRIPTION
**Pull request by neon60**
Handle the return value in malloc_and_free.h. 
Issue: #163

### CODE REVIEW

**Review by doctorcolinsmith — APPROVED** [review]
The change looks fine, but there is a CI fail due to an aborted build.  Should re-run that before merging.

**Review by saadrahim — COMMENTED** [review]
Are we missing something in our test suite that this was not caught?

**Comment by neon60** [comment]
> Are we missing something in our test suite that this was not caught?

We can discuss this in the evenging. I could not reproduce the warning, but it should appear. We need further investigation.

**Comment by neon60** [comment]
> > Are we missing something in our test suite that this was not caught?
> 
> We can discuss this in the evenging. I could not reproduce the warning, but it should appear. We need further investigation.

Found he issue:
```
if(DISABLE_WERROR)
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wall -Wextra")
else()
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wall -Wextra -Werror")
endif()
```

Somehow we deleted these lines.

**Comment by andrewcorrigan** [comment]
Thank you for so quickly addressing this.  Would it be possible to get the two other instances while you're taking care of this one?

- [thrust/system/hip/detail/util.h:189](https://github.com/ROCmSoftwarePlatform/rocThrust/blob/develop/thrust/system/hip/detail/util.h#L189)
- [thrust/system/hip/detail/util.h:221](https://github.com/ROCmSoftwarePlatform/rocThrust/blob/develop/thrust/system/hip/detail/util.h#L221)

**Comment by neon60** [comment]
> Thank you for so quickly addressing this. Would it be possible to get the two other instances while you're taking care of this one?
> 
> * [thrust/system/hip/detail/util.h:189](https://github.com/ROCmSoftwarePlatform/rocThrust/blob/develop/thrust/system/hip/detail/util.h#L189)
> * [thrust/system/hip/detail/util.h:221](https://github.com/ROCmSoftwarePlatform/rocThrust/blob/develop/thrust/system/hip/detail/util.h#L221)

Thanks for the notification. It's in the next PR: #166

**Comment by neon60** [comment]
> > > Are we missing something in our test suite that this was not caught?
> > 
> > 
> > We can discuss this in the evenging. I could not reproduce the warning, but it should appear. We need further investigation.
> 
> Found the issue:
> 
> ```
> if(DISABLE_WERROR)
>   set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wall -Wextra")
> else()
>   set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wall -Wextra -Werror")
> endif()
> ```
> 
> Somehow we deleted these lines.

@saadrahim we still could not reproduce the reported warning after the fix. I will do more investigation, why not?

**Comment by neon60** [comment]
We can close this PR, if we want. The PR #166 covers this changeset.

**Comment by stanleytsang-amd** [comment]
Closing this PR as this is covered by $166.

**Pull request closed without merging**
