### PR TITLE
Merging warning fixes from develop

### PR DESCRIPTION
**Pull request by stanleytsang-amd**

### CODE REVIEW

**Comment by saadrahim** [comment]
Please revert with hard overwrite of history

**Comment by saadrahim** [comment]
You should only fast forward

**Comment by saadrahim** [comment]
Git checkout staging 
Git reset --hard origin/develop 
Git push origin staging

**Comment by stanleytsang-amd** [comment]
Sorry about that.  Done as instructed.

**Comment by saadrahim** [comment]
Thanks, it has been just me for a long time. We should document someday.

**Pull request merged**
