### PR TITLE
doc reorganization

### PR DESCRIPTION
**Pull request by randyh62**
updated Installation instructions for later version and also for git clone command
updated Index and TOC
Updated device_malloc.h for overloaded param 'n'

### CODE REVIEW

**Comment by Rmalavally** [comment]
@randyh62 How can I help? Why is this assigned to me?

**Comment by randyh62** [comment]
@samjwu and @yhuiYH the Read the Docs process failed on this PR, but provides no feedback for why or how it failed. Sam, this is the rocThrust repo that was failing because of the \overload param, which you fixed previously but was removed. I restored your change as part of this PR and it builds locally for me, but not here. I don't know if this is related to the failure here, but thought it was worth mentioning. Can either of you identify why this PR might be failing?

**Comment by samjwu** [comment]
@randyh62 

the overload param is not needed, the doxygen error was a bug for 1.8

the syntax is correct in the develop branch. the bug was fixed in doxygen 1.9.8

I set RTD custom env here: https://github.com/ROCm/rocThrust/blob/develop/docs/environment.yml

**Comment by randyh62** [comment]
Reverted \overload change in device_malloc.h

**Comment by randyh62** [comment]
Would anyone like to review or approve this reorganization? Seems a simple thing, but I can make any needed changes. Thanks.

**Review by stanleytsang-amd — APPROVED** [review]

**Comment by stanleytsang-amd** [comment]
looks good to me.

**Comment by randyh62** [comment]
Thank you.

**Pull request merged**
