### PR TITLE
Fix rocThrust building failure due to hcc codes removed from hip

### PR DESCRIPTION
**Pull request by tomsang**
Change  HIP_INCLUDE_HIP_HCC_DETAIL_DRIVER_TYPES_H into
HIP_INCLUDE_HIP_AMD_DETAIL_DRIVER_TYPES_H

Change HIP_INCLUDE_HIP_HCC_DETAIL_HOST_DEFINES_H into 
HIP_INCLUDE_HIP_AMD_DETAIL_HOST_DEFINES_H

### CODE REVIEW

**Comment by tomsang** [comment]
The jenkin tests need the latest codes of hip

**Comment by saadrahim** [comment]
You are introducing a new file without first deprecating the older file. This type of change does not maintain backward compatibility. It cannot be in public code compiles with the last released rocm version.

**Comment by tomsang** [comment]
Originally files are deprecated.  New files  have entered amd-staging branch in gerrit. 
This PR need wait for the new files  to enter main line.

**Comment by doctorcolinsmith** [comment]
The changed file name should be considered a breaking API change from the HIP runtime, which does not work with AMD's API compatibility polices.  We need to work internally to see if we can accept this change.

**Comment by tomsang** [comment]
The patch for compatibility is merged today.    This PR can  be valid only after the patch enters main line.  please hold on.

**Comment by tomsang** [comment]
HIP_INCLUDE_HIP_HCC_DETAIL_DRIVER_TYPES_H/HIP_INCLUDE_HIP_HCC_DETAIL_HOST_DEFINES_H
HIP_INCLUDE_HIP_AMD_DETAIL_DRIVER_TYPES_H/HIP_INCLUDE_HIP_AMD_DETAIL_HOST_DEFINES_H

All above are  hip internal macros that are not expected to be referenced by upstream.

A better solution is not to depend on such macros.

**Comment by saadrahim** [comment]
Will merge after 4.1 is released.

**Review by saadrahim — COMMENTED** [review]
I think we are ready to accept this PR. Anyone have any concerns?

**Review by saadrahim — APPROVED** [review]
I am approving this change as no one else has raised objections.

**Review by neon60 — APPROVED** [review]

**Pull request merged**
