### PR TITLE
Develop stream 2024-07-03

### LINKED ISSUE #420: [Issue]: Failing tests with libstdc++ assertions due to unsigned overflow
### Problem Description

The issue is similar to https://github.com/ROCm/rocPRIM/issues/570.

With hardened libstdc++ (compiled with -D_GLIBCXX_ASSERTIONS), few tests rocThrust 6.1.1 fail with:
```
[ RUN      ] AsyncReduceTests/3.TestAsyncReduce
/usr/lib/gcc/x86_64-pc-linux-gnu/13/include/g++-v13/bits/uniform_int_dist.h:108: std::uniform_int_distribution<unsigned short>::param_type::param_type(_IntType, _IntType) [_IntType = unsigned short]: Assertion '_M_a <= _M_b' failed.

[ RUN      ] AsyncTransformTests/3.TestAsyncTransformUnary
/usr/lib/gcc/x86_64-pc-linux-gnu/13/include/g++-v13/bits/uniform_int_dist.h:108: std::uniform_int_distribution<unsigned short>::param_type::param_type(_IntType, _IntType) [_IntType = unsigned short]: Assertion '_M_a <= _M_b' failed.

[ RUN      ] PrimitiveGatherTests/0.Gather
/usr/lib/gcc/x86_64-pc-linux-gnu/13/include/g++-v13/bits/uniform_int_dist.h:108: std::uniform_int_distribution<unsigned int>::param_type::param_type(_IntType, _IntType) [_IntType = unsigned int]: Assertion '_M_a <= _M_b' failed.

[ RUN      ] PrimitiveInnerProductTests/0.InnerProductWithRandomData
/usr/lib/gcc/x86_64-pc-linux-gnu/13/include/g++-v13/bits/uniform_int_dist.h:108: std::uniform_int_distribution<short>::param_type::param_type(_IntType, _IntType) [_IntType = short]: Assertion '_M_a <= _M_b' failed.

[ RUN      ] ScanByKeyTests.TestScanByKeyMixedTypes
/usr/lib/gcc/x86_64-pc-linux-gnu/13/include/g++-v13/bits/uniform_int_dist.h:108: std::uniform_int_distribution<unsigned int>::param_type::param_type(_IntType, _IntType) [_IntType = unsigned int]: Assertion '_M_a <= _M_b' failed.
```

In lines like `get_random_data<T>(2, -100, 100, seed)` tests attempt to generate `T=unsigned int` in range, where min (4294967196) > max (100), which is undefined behavior. Can you fix it (and maybe in rocPRIM too)? Thanks!

### Operating System

Gentoo

### CPU

-

### GPU

AMD Instinct MI300X

### ROCm Version

ROCm 6.1.0

### ROCm Component

_No response_

### Steps to Reproduce

_No response_

### (Optional for Linux users) Output of /opt/rocm/bin/rocminfo --support

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by Naraenda**
This PR adds the changes intended for ROCm 6.3 and contains the following merge commits:

* bd2aa5ea ci: internal fix for windows builds
* 0bfd2c6c test: ensure tests pass with hardened libstdc++ (closes https://github.com/ROCm/rocThrust/issues/420)
* 46281162 feat: add policy for run-to-run (on same device) determinism
* e8a247e8 docs: fix various warnings
* c8f939c9 test: add openmp backend tests
* 1353cb05 feat: synchronise with thrust 2.3.2
* e93ef355 ci: fix copyright checker script not always detecting copyright
* db108ae6 docs: update changelog
* 921f9097 refactor: use rocprim::uninitialized_array in set_operations
* 7e0d6c6f test: enable upstream test suite
* 14b8f394 fix: use the exact rocprim partition function and parameters for temporary memory size
* 4221430a ci: add windows ci

This PR is dependent on https://github.com/ROCm/rocPRIM/pull/575.

### CODE REVIEW

**Comment by stanleytsang-amd** [comment]
@Naraenda Looking through this PR, I noticed we're missing interfaces for inplace_merge, partial_sort, partial_sort_copy, nth_element to be compatible with the ParallelSTL/hipstdpar header https://github.com/ROCm/rocThrust/blob/develop/thrust/system/hip/hipstdpar/hipstdpar_lib.hpp.

Would it be possible to add basic wrapper interfaces in rocThrust for these functions (and future hipstdpar functions)?

**Comment by Naraenda** [comment]
Should it not be added to https://github.com/ROCm/roc-stdpar/blob/main/include/hipstdpar_lib.hpp?

**Comment by stanleytsang-amd** [comment]
> Should it not be added to https://github.com/ROCm/roc-stdpar/blob/main/include/hipstdpar_lib.hpp?

I have confirmed that the rocThrust copy of the hipstdpar_lib.hpp is the sole source of truth and is the one that needs to be modified.  The roc-stdpar was created for convenience but it is not actively maintained.

**Comment by Naraenda** [comment]
@stanleytsang-amd The CI is showing some build failures, but we're not seeing the same in our own CI. Could you send the logs so we can investigate it on our end as well?

**Comment by stanleytsang-amd** [comment]
> @stanleytsang-amd The CI is showing some build failures, but we're not seeing the same in our own CI. Could you send the logs so we can investigate it on our end as well?

I wouldn't worry too much about the build failures at the moment - I asked to start a CI run on rocThrust before the entirety of the rocPRIM PR passed to get an earlier start on the review process.  However since at that time there were multiple pipelines in the rocPRIM PR that were failing due to inplace_merge, the corresponding CI pipelines for this PR would grab from head of the develop branch, causing build failures for the deterministic functions.

Now that the rocPRIM PR  has passed completely, I'll trigger a new CI run for rocThrust and hipCUB.  Check back again later today or tomorrow morning.

**Review by stanleytsang-amd — APPROVED** [review]

**Pull request merged**
