### PR TITLE
Handle the size zero inputs when grid/block dim minimum size is 1.

### PR DESCRIPTION
**Pull request by neon60**
Handle the size zero inputs when grid/block dim minimum size is 1.

### CODE REVIEW

**Comment by neon60** [comment]
Could someone send the error message of the failure?

**Comment by stanleytsang-amd** [comment]
> Could someone send the error message of the failure?

I will email you a log of the failures.

**Comment by saadrahim** [comment]
It appears to be internal infrastructure issues. Confirming soon.

**Comment by neon60** [comment]
Tested with the docker image. It's working.

**Comment by stanleytsang-amd** [comment]
Can confirm, all tests now passing with this PR.  I will merge this one and close my bandaid PR.

**Review by stanleytsang-amd — APPROVED** [review]

**Pull request merged**
