### PR TITLE
Adding option to force install GTest. 

### PR DESCRIPTION
**Pull request by stanleytsang-amd**
Also making it force install GTest 1.10 by default on jenkins CI.  Looks like we're grabbing an older version of Gtest there, causing CI failures.

### CODE REVIEW

**Comment by eidenyoshida** [comment]
Can you provide an example of CI having the wrong version of gtest? We might need to fix something in CI if that's the case

**Comment by stanleytsang-amd** [comment]
> Can you provide an example of CI having the wrong version of gtest? We might need to fix something in CI if that's the case

If you take a look at any of the CI failures since the HIP on Windows commit in the develop branch (where I added the requirement for Gtest 1.10 and added a find_package check beforehand to Dependencies.cmake), you should be able to see that most if not all of them are failing during compilation.  All of which are failing due to Gtest in some shape or form.  From my experience those messages are consistent with older version of gtest being found.

**Comment by saadrahim** [comment]
All below is from Eiden:```

Failure is likely cause by I think moving

include(cmake/Dependencies.cmake) 

before

set(AMDGPU_TARGETS "${DEFAULT_AMDGPU_TARGETS}" CACHE STRING "List of specific machine types for library to target")

sets AMDGPU_TARGETS prematurely because dependencies.cmake does find_package(rocprim) which causes find_package(hip) which sets AMDGPU_TARGETS

I think something is broken in rocThrust compilation in CI. It hasn't been targeting the right device targets since this commit https://github.com/ROCmSoftwarePlatform/rocThrust/commit/22fda4adfced5be5addec35b16050d7ffc99a67e
 
Last passing
http://math-ci.rocm.amd.com/blue/organizations/jenkins/compute-rocm-dkms-no-npi-hipclang%2Fprecheckin%2FrocThrust/detail/develop/134/pipeline/210/#step-225-log-172

Device targets : gfx803;gfx900:xnack-;gfx906:xnack-;gfx908:xnack-;gfx90a:xnack-;gfx90a:xnack+;gfx1030

 

First fail

http://math-ci.rocm.amd.com/blue/organizations/jenkins/compute-rocm-dkms-no-npi-hipclang%2Fprecheckin%2FrocThrust/detail/develop/135/pipeline/217

Device targets : gfx900;gfx906;gfx908
```

**Comment by stanleytsang-amd** [comment]
Upon further investigation, the root cause is not because of an older version of GTest being installed, but a combination of trying to build a test executable with no test case (device_delete) and using GTest static library.
Adding the test case back (even if it is empty) fixed the issue locally for me.  And linking to Gtest as a shared library also seems to avoid the problem.

**Review by eidenyoshida — APPROVED** [review]

**Comment by saadrahim** [comment]
The title of the PR was likely incorrect.

**Pull request merged**
