### PR TITLE
Updating CHANGELOG and version for ROCm 4.1

### PR DESCRIPTION
**Pull request by stanleytsang-amd**
Fixing changelog

### CODE REVIEW

**Comment by saadrahim** [comment]
@stanleytsang-amd is this a stale PR?

**Comment by stanleytsang-amd** [comment]
> @stanleytsang-amd is this a stale PR?

Yeah.  I will just merge this in.  The CI failures have nothing to do with these changes.

**Comment by saadrahim** [comment]
I don't think you should merge now.

**Comment by saadrahim** [comment]
Until we release, it should not go in. I think the correct process is to merge from this from the release candidate branch. Ofcourse, I am making the process up as we go.

**Comment by stanleytsang-amd** [comment]
Stale PR, will merge in updated CHANGELOG from 4.1 release branch.

**Pull request closed without merging**
